- name: Listen for new messages from kafka
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: 172.30.196.226
        port: 9092
        topic: kafka-eda
        group_id:
  rules:
    - name: kafka
      condition: event.message == "Ansible is cool"
      action:
        run_job_template:
          name: kafka-ndcmgmt-cluster
          organization: Default
